import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Autogenerated from the docs folder, so every generated skill page appears
// under its category with collapsible groups, matching the upstream layout.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
